from enum import Enum, unique

@unique
class MedicalSpecialization(Enum):
    CARDIOLOGY = "cardiology"
    DERMATOLOGY = "dermatology"
    ENDOCRINOLOGY = "endocrinology"
    FAMILY_MEDICINE = "family-medicine"
    GASTROENTEROLOGY = "gastroenterology"
    HEMATOLOGY = "hematology"
    INFECTIOUS_DISEASE = "infectious-disease"
    INTERNAL_MEDICINE = "internal-medicine"
    NEPHROLOGY = "nephrology"
    NEUROLOGY = "neurology"
    OBSTETRICS_GYNECOLOGY = "obstetrics-and-gynecology"
    ONCOLOGY = "oncology"
    OPHTHALMOLOGY = "ophthalmology"
    ORTHOPEDICS = "orthopedics"
    PEDIATRICS = "pediatrics"
    PSYCHIATRY = "psychiatry"
    PULMONOLOGY = "pulmonology"
    RADIOLOGY = "radiology"
    RHEUMATOLOGY = "rheumatology"
    SURGERY = "general-surgery"
    UROLOGY = "urology"
